services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'findyourguide'
    environment:
      - 'MARIADB_DATABASE=findyourguide'
      - 'MARIADB_PASSWORD=2908'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=fmartinezvidal'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_volume:/var/lib/mysql

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: 'phpmyadmin'
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=fmartinezvidal
      - PMA_PASSWORD=2908
    ports:
      - '8081:80'
    depends_on:
      - mariadb

volumes:
  mariadb_volume:
